name: conda
channels:
  - conda-forge
dependencies:
  - python
  - spyder-env 
  - numpy 
  - spyder 
  - scipy 
  - pandas 
  - matplotlib 
  - sympy 
  - cython
  - upgrade spyder
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery