name: conda
channels:
  - conda-forge
dependencies:
  - python
  - spyder-env 
  - numpy 
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
	- spyder 
	- scipy 
	- pandas 
	- matplotlib 
	- sympy 
	- cython
	- upgrade spyder